export enum ChainVisibilityEnum {
  VISIBILITY_TYPE_UNSPECIFIED = 'VISIBILITY_TYPE_UNSPECIFIED',
  VISIBILITY_TYPE_PUBLIC_READ = 'VISIBILITY_TYPE_PUBLIC_READ',
  VISIBILITY_TYPE_PRIVATE = 'VISIBILITY_TYPE_PRIVATE',
  VISIBILITY_TYPE_INHERIT = 'VISIBILITY_TYPE_INHERIT',
  UNRECOGNIZED = 'UNRECOGNIZED',
}
