name: Add labels

on:
  issue_comment:
    types: [created, edited]

jobs:
  Add-Labels:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/add-labels:')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Parse comment by github script
        uses: actions/github-script@v6
        id: parse-comment
        with:
          script: |
            const script = require('${{ github.workspace }}/.github/utils/add-labels-by-comment.js');
            await script({github, context, core});
          reactions: hooray, rocket
