name: Dcellar-web-ui prod mainnet CICD

on:
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      project:
        description: "Select a project to deploy."
        required: true
        default: "dcellar-web-ui"
        options: ["dcellar-web-ui"]
        type: choice
      environment:
        description: "Choose the environment for deployment."
        required: true
        default: "mainnet"
        options: ["testnet"]
        type: choice
      ref:
        description: "Choose the branch for deployment"
        required: true
        default: "mainnet-main"
        options: ["mainnet-main"]
        type: choice

jobs:
  pre-check:
    runs-on: ubuntu-latest
    if: ((github.event.inputs.project == 'dcellar-web-ui') && (github.event.inputs.environment == 'mainnet'))
    outputs:
      codeowners: ${{ steps.codeowners.outputs.content }}
      ref: ${{ steps.trim_ref.outputs.ref }}
    steps:
    - name: Trim ref value
      id: trim_ref
      run: |
        REF=$(echo "${{ github.event.inputs.branch }}" | xargs)
        echo "ref=$REF" >> $GITHUB_OUTPUT
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Read codeowners
      id: codeowners
      uses: juliangruber/read-file-action@v1
      with:
        path: .github/CODEOWNERS
  check-codeowners:
    runs-on: ubuntu-latest
    needs: [pre-check]
    if: (!contains(needs.pre-check.outputs.codeowners, github.event.comment.user.login))
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Create Version Comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.issue.number }}
        comment-id: ${{ github.event.comment.id }}
        body: |
          ++++++
          Deployment request denied. Please ensure you have the necessary permissions by contacting the project code owners.
        reactions: rocket
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CICD:
    needs: [pre-check]
    if: (contains(needs.pre-check.outputs.codeowners, github.event.comment.user.login))
    uses: node-real/public-github-workflows/.github/workflows/dcellar-web-ui-prod-mainnet-cicd.yml@main
    secrets: inherit
    with:
      app_name: dcellar-web-ui
      env: mainnet
      ref: mainnet-main