name: dcellar-web-ui qa CICD

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App name in GitOps is used for branch naming only.'
        type: string
        required: true
        default: 'dcellar-web-ui'
      env:
        description: 'Specify the deployment environment'
        type: string
        required: true
        default: 'qa'

jobs:
  CICD:
    uses: node-real/public-github-workflows/.github/workflows/dcellar-web-ui-qa-cicd.yml@main
    secrets: inherit
    with:
      app_name: ${{ inputs.app_name }}
      env: ${{ inputs.env }}
